server:
  port: 8090
  servlet:
    context-path: /demo
#集成hibernate
spring:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        new_generator_mappings: false
#        format_sql: true
  task:
    scheduling:
      pool:
        size: 8
      #用于新创建线程名称的前缀。
      thread-name-prefix: springboot-self-
      shutdown:
        await-termination: true
        #执行程序是否应等待计划任务在关机时完成
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: testUser
    password: Tu123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
#    publisher-confirms: true #开启消息确认机制：已经过期
#    publisherConfirmType: NONE
#      SIMPLE,在范围操作中使用RabbitTemplate#waitForConfirms() （或waitForConfirmsOrDie()
#      CORRELATED, 与CorrelationData一起使用以将确认与发送的消息相关联。
#      NONE：发布者确认被禁用（默认）。
#    publisher-returns: true #支持消息发送失败返回队列
#    listener:
#      type: simple
#      simple:
#        default-requeue-rejected: false
#        acknowledge-mode: manual
  redis:
    # Redis服务器地址
    host: localhost
    #Redis服务器连接端口
    port: 6379
    #password:
    # Redis数据库索引（默认为0）
    database: 1
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
#注意pom依赖，不要用单独的mybatis，否则这里会实例化失败sqlSessionFactory，需要你手动实例化；应该使用springboot集成的mybatis starter
mybatis:
  configuration:
    #在Springboot中，可以通过设置map-underscore-to-camel-case属性为true来开启驼峰功能。
    map-underscore-to-camel-case: true
  # 配置实体地址
  type-aliases-package: com.xiaocai.bootreview.ssm.entity
  # 配置Mapper.xml地址
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.xiaocai.bootreview.ssm.mapper: debug
    java.sql.ResultSet: INFO
    org.apache: INFO
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    java.sql.PreparedStatement: DEBUG
    com.rjxy.aowu.dao: TRACE
#    原文链接：https://blog.csdn.net/weixin_43592699/article/details/109829105
#自定义私信队列配置
app:
  rabbitmq:
    # 队列定义
    queue:
      user: user-queue
      dead: user-dead-queue
    # 交换机定义
    exchange:
      user: user-exchange
      dead: user-dead-exchange
#  原文链接：https://blog.csdn.net/weixin_44507274/article/details/105469344